services:
  trufi-tileserver-gl:
    image: maptiler/tileserver-gl:latest
    container_name: trufi-tileserver-gl
    ports:
      - "5656:8080"
    volumes:
      - ./data:/data
    command: tileserver-gl -p 8080 
    restart: unless-stopped
    networks:
      - trufi-server

networks:
  trufi-server:
    name: trufi-server
